### ISSUE TITLE
Missing Capitals

### ISSUE THREAD

**Issue by edwardchalstrey1** [MajidBenam/seshat#11]
Hi @MajidBenam I'm looking at visualising capital cities on the world map I've developed using lat/lon coordinates, which I get from the `core.capital` model/table, linking via the `general.polity_capital` which is associated with a page and has the capital, but not coordinates. When I match the `capital` field of that table to the `name` field of `core.capital` I get some matches, but I noticed that many are missing. In other words there's quite a few Seshat polity pages where a capital is recorded, but we don't have coordinates.

Do you think this is something likely to change in the near future? I'm not sure there is a mechanism for Seshat users to add the coordinates via the update page? If not, I may just suppress this feature of the world map for now.

**Comment by MajidBenam** [comment]
Hi @edwardchalstrey1 
Your insight has drawn my attention to the management of capitals, prompting me to initiate some adjustments to our data schema regarding polities/capitals. Under the new framework, we will introduce `core_capital` instances, devoid of any attached polities but retaining all other attributes. Instead, a new foreign key will be added to the `general_polity_capital` class, directing to instances of the `Capital` model. This adjustment is expected to mitigate modeling issues and enhance the accessibility and editability of capitals.

However, addressing the issue where some polities have string representations of capitals but lack actual longitude and latitude data will require a comprehensive solution. I will ensure that existing coded string capitals (general_polity_capitals) are augmented to point to existing `core_capital` instances. Additionally, I will streamline the process of editing capitals, making it more straightforward for Research Assistants (RAs). 

It's important to note that adding new information on new capitals or existing string capitals will continue to be a task primarily undertaken by RAs, and such processes typically progress at a slower pace.

**Comment by edwardchalstrey1** [comment]
Great, thanks Majid! Ok sounds good, I'll incorporate your updates but I'll work on the assumption that it could be a while on the coordinates being available

**Comment by edwardchalstrey1** [comment]
Closing as this is more of an issue of data entry by RAs
