### ISSUE TITLE
Reproducible deployment

### ISSUE THREAD

**Issue by edwardchalstrey1** [MajidBenam/seshat#4]
It could be useful to extend the instructions to support re-deployment of the website if needed, for example if the AWS server VM was accidentally deleted or corrupted in some way.

For example, these instructions could provide setup steps similar to what has been added for a [local setup](https://github.com/MajidBenam/seshat/blob/dev/docs/setup.md), but with additional/modified steps to correctly configure the cloud VM. That way, so long as a backup of the database is available, this paired with the code from GitHub will mean there is no chance to lose the site, and it could also be hosted elsewhere if needed.

A stretch goal could be to write scripts with an infrastructure-as-code tool such as Pulumi or Terraform which can automate this deployment.

**Comment by MajidBenam** [comment]
This is an excellent suggestion as well, and it's crucial for ensuring a smoother experience. No one wants to deal with server hiccups and potential data losses. I've always been diligent about keeping database backups and notes for redeployment, but I haven't quite reached that desired automation level with clean scripts.

Terraform does seem like a solid choice, given its simplicity and AWS integration. While I'm still getting up to speed with Terraform, if you've got the know-how and the inclination to take the lead on this, I'm all for it. However, if you'd rather not or do not have the time, I'll definitely roll up my sleeves and give it a shot in the near future.

**Comment by edwardchalstrey1** [comment]
Proposed development plan for working on this at Turing, bearing in mind there could be a delay in getting a credited AWS subscription:
1. Attempt to set up a dev Seshat environment on a linux VM on Azure using our existing project subscription which can be viewed at a url and document the manual steps
2. Translate these steps into IAC (Pulumi or Terraform) and test on Azure
3. In tandem, speak to Turing IT about getting access to credited AWS subscription
4. Test deployment on AWS and update IAC code as needed

Note: it may be easier to get set up with AWS at Turing than I expect, in which case we can skip the Azure steps

**Comment by edwardchalstrey1** [comment]
Current docs:

- Majid notion docs: https://www.notion.so/Seshat-Backup-Server-0c0efee3f4344a78a4b8fe855b78bff1
- Ed's GitHub docs: https://github.com/edwardchalstrey1/seshat/blob/dev/docs/setup.md

**Comment by edwardchalstrey1** [comment]
Linked issue on fork: https://github.com/edwardchalstrey1/seshat/issues/79

**Comment by edwardchalstrey1** [comment]
Also closing this to reduce duplicate issues: https://github.com/edwardchalstrey1/seshat/issues/79
